version: "3.8"

services:
  mysql_db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nestjs
    restart: always
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3307
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: test
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
