name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # - name: Install Docker Compose
      #   run: |
      #     sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      #     sudo chmod +x /usr/local/bin/docker-compose
      #     docker-compose --version

      - name: Build NestJS Docker image
        run: |
          docker build -t nestjs-app .

      # - name: Run Docker Compose (up -d)
      #   run: |
      #     docker-compose -f docker-compose.yml up -d

      # - name: Wait for MySQL to be ready
      #   run: |
      #     docker exec mysql mysqladmin --host=127.0.0.1 --user=root --password=root ping --silent

      # - name: Run Tests
      #   run: |
      #     docker exec nestjs npm run test

      - name: Rebuild NestJS Docker container
        run: |
          docker compose down
          docker compose up -d --build --remove-orphans

      - name: Clean up Docker images
        run: |
          docker system prune -a --volumes -f
